"""IND-2g -- generated TA-Lib catalog snapshot, part 6 of 10.

DO NOT EDIT BY HAND -- regenerate with
`python -m src.core.indicators.catalog.generate_from_talib`. Imports nothing
beyond the stdlib so it loads without TA-Lib installed (snapshot-only
verification, see `generate_from_talib.py` module docstring).
"""
from __future__ import annotations

TALIB_GENERATED_PART: tuple[dict[str, object], ...] = (
    {'name': 'LN',
 'group': 'Math Transform',
 'inputs': ['close'],
 'params': [],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'LOG10',
 'group': 'Math Transform',
 'inputs': ['close'],
 'params': [],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'MA',
 'group': 'Overlap Studies',
 'inputs': ['close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30},
            {'name': 'matype', 'min': 0, 'max': 8, 'default': 0}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'MACD',
 'group': 'Momentum Indicators',
 'inputs': ['close'],
 'params': [{'name': 'fastperiod', 'min': 1, 'max': 2000, 'default': 12},
            {'name': 'slowperiod', 'min': 1, 'max': 2000, 'default': 26},
            {'name': 'signalperiod', 'min': 1, 'max': 2000, 'default': 9}],
 'outputs': ['macd', 'macdsignal', 'macdhist'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None},
           {'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None},
           {'kind': 'histogram',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': 'sign',
            'precision': None,
            'legend_format': None}]},
    {'name': 'MACDEXT',
 'group': 'Momentum Indicators',
 'inputs': ['close'],
 'params': [{'name': 'fastperiod', 'min': 1, 'max': 2000, 'default': 12},
            {'name': 'fastmatype', 'min': 0, 'max': 8, 'default': 0},
            {'name': 'slowperiod', 'min': 1, 'max': 2000, 'default': 26},
            {'name': 'slowmatype', 'min': 0, 'max': 8, 'default': 0},
            {'name': 'signalperiod', 'min': 1, 'max': 2000, 'default': 9},
            {'name': 'signalmatype', 'min': 0, 'max': 8, 'default': 0}],
 'outputs': ['macd', 'macdsignal', 'macdhist'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None},
           {'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None},
           {'kind': 'histogram',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': 'sign',
            'precision': None,
            'legend_format': None}]},
    {'name': 'MACDFIX',
 'group': 'Momentum Indicators',
 'inputs': ['close'],
 'params': [{'name': 'signalperiod', 'min': 1, 'max': 2000, 'default': 9}],
 'outputs': ['macd', 'macdsignal', 'macdhist'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None},
           {'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None},
           {'kind': 'histogram',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': 'sign',
            'precision': None,
            'legend_format': None}]},
    {'name': 'MAMA',
 'group': 'Overlap Studies',
 'inputs': ['close'],
 'params': [],
 'outputs': ['mama', 'fama'],
 'plots': [{'kind': 'line',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None},
           {'kind': 'line',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'MAVP',
 'group': 'Overlap Studies',
 'inputs': ['close', 'periods'],
 'params': [{'name': 'minperiod', 'min': 1, 'max': 2000, 'default': 2},
            {'name': 'maxperiod', 'min': 1, 'max': 2000, 'default': 30},
            {'name': 'matype', 'min': 0, 'max': 8, 'default': 0}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'MAX',
 'group': 'Math Operators',
 'inputs': ['close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'MAXINDEX',
 'group': 'Math Operators',
 'inputs': ['close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
 'outputs': ['integer'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'MEDPRICE',
 'group': 'Price Transform',
 'inputs': ['high', 'low'],
 'params': [],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'MFI',
 'group': 'Momentum Indicators',
 'inputs': ['high', 'low', 'close', 'volume'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'MIDPOINT',
 'group': 'Overlap Studies',
 'inputs': ['close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]}
)
