"""IND-2g -- generated TA-Lib catalog snapshot, part 2 of 10.

DO NOT EDIT BY HAND -- regenerate with
`python -m src.core.indicators.catalog.generate_from_talib`. Imports nothing
beyond the stdlib so it loads without TA-Lib installed (snapshot-only
verification, see `generate_from_talib.py` module docstring).
"""
from __future__ import annotations

TALIB_GENERATED_PART: tuple[dict[str, object], ...] = (
    {'name': 'CDLCOUNTERATTACK',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLDARKCLOUDCOVER',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLDOJI',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLDOJISTAR',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLDRAGONFLYDOJI',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLENGULFING',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLEVENINGDOJISTAR',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLEVENINGSTAR',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLGAPSIDESIDEWHITE',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLGRAVESTONEDOJI',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLHAMMER',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLHANGINGMAN',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLHARAMI',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLHARAMICROSS',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLHIGHWAVE',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLHIKKAKE',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLHIKKAKEMOD',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLHOMINGPIGEON',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]}
)
