"""IND-2g -- generated TA-Lib catalog snapshot, part 1 of 10.

DO NOT EDIT BY HAND -- regenerate with
`python -m src.core.indicators.catalog.generate_from_talib`. Imports nothing
beyond the stdlib so it loads without TA-Lib installed (snapshot-only
verification, see `generate_from_talib.py` module docstring).
"""
from __future__ import annotations

TALIB_GENERATED_PART: tuple[dict[str, object], ...] = (
    {'name': 'BBANDS',
 'group': 'Overlap Studies',
 'inputs': ['close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 5},
            {'name': 'matype', 'min': 0, 'max': 8, 'default': 0}],
 'outputs': ['upperband', 'middleband', 'lowerband'],
 'plots': [{'kind': 'band',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': 'lowerband',
            'color_rule': None,
            'precision': None,
            'legend_format': None},
           {'kind': 'line',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None},
           {'kind': 'band',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': 'upperband',
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'BETA',
 'group': 'Statistic Functions',
 'inputs': ['high', 'low'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 5}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'BOP',
 'group': 'Momentum Indicators',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CCI',
 'group': 'Momentum Indicators',
 'inputs': ['high', 'low', 'close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDL2CROWS',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDL3BLACKCROWS',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDL3INSIDE',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDL3LINESTRIKE',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDL3OUTSIDE',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDL3STARSINSOUTH',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDL3WHITESOLDIERS',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLABANDONEDBABY',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLADVANCEBLOCK',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLBELTHOLD',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLBREAKAWAY',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLCLOSINGMARUBOZU',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLCONCEALBABYSWALL',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]}
)
