"""IND-2g -- generated TA-Lib catalog snapshot, part 4 of 10.

DO NOT EDIT BY HAND -- regenerate with
`python -m src.core.indicators.catalog.generate_from_talib`. Imports nothing
beyond the stdlib so it loads without TA-Lib installed (snapshot-only
verification, see `generate_from_talib.py` module docstring).
"""
from __future__ import annotations

TALIB_GENERATED_PART: tuple[dict[str, object], ...] = (
    {'name': 'CDLSHOOTINGSTAR',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLSHORTLINE',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLSPINNINGTOP',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLSTALLEDPATTERN',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLSTICKSANDWICH',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLTAKURI',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLTASUKIGAP',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLTHRUSTING',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLTRISTAR',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLUNIQUE3RIVER',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLUPSIDEGAP2CROWS',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLXSIDEGAP3METHODS',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CEIL',
 'group': 'Math Transform',
 'inputs': ['close'],
 'params': [],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CMO',
 'group': 'Momentum Indicators',
 'inputs': ['close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CORREL',
 'group': 'Statistic Functions',
 'inputs': ['high', 'low'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'COS',
 'group': 'Math Transform',
 'inputs': ['close'],
 'params': [],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'COSH',
 'group': 'Math Transform',
 'inputs': ['close'],
 'params': [],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'DEMA',
 'group': 'Overlap Studies',
 'inputs': ['close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]}
)
