"""IND-2g -- generated TA-Lib catalog snapshot, part 8 of 10.

DO NOT EDIT BY HAND -- regenerate with
`python -m src.core.indicators.catalog.generate_from_talib`. Imports nothing
beyond the stdlib so it loads without TA-Lib installed (snapshot-only
verification, see `generate_from_talib.py` module docstring).
"""
from __future__ import annotations

TALIB_GENERATED_PART: tuple[dict[str, object], ...] = (
    {'name': 'ROCR100',
 'group': 'Momentum Indicators',
 'inputs': ['close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 10}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'RSI',
 'group': 'Momentum Indicators',
 'inputs': ['close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'SAR',
 'group': 'Overlap Studies',
 'inputs': ['high', 'low'],
 'params': [],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'SAREXT',
 'group': 'Overlap Studies',
 'inputs': ['high', 'low'],
 'params': [],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'SIN',
 'group': 'Math Transform',
 'inputs': ['close'],
 'params': [],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'SINH',
 'group': 'Math Transform',
 'inputs': ['close'],
 'params': [],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'SMA',
 'group': 'Overlap Studies',
 'inputs': ['close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'SQRT',
 'group': 'Math Transform',
 'inputs': ['close'],
 'params': [],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'STDDEV',
 'group': 'Statistic Functions',
 'inputs': ['close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 5}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'STOCH',
 'group': 'Momentum Indicators',
 'inputs': ['high', 'low', 'close'],
 'params': [{'name': 'fastk_period', 'min': 1, 'max': 2000, 'default': 5},
            {'name': 'slowk_period', 'min': 1, 'max': 2000, 'default': 3},
            {'name': 'slowk_matype', 'min': 0, 'max': 8, 'default': 0},
            {'name': 'slowd_period', 'min': 1, 'max': 2000, 'default': 3},
            {'name': 'slowd_matype', 'min': 0, 'max': 8, 'default': 0}],
 'outputs': ['slowk', 'slowd'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None},
           {'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'STOCHF',
 'group': 'Momentum Indicators',
 'inputs': ['high', 'low', 'close'],
 'params': [{'name': 'fastk_period', 'min': 1, 'max': 2000, 'default': 5},
            {'name': 'fastd_period', 'min': 1, 'max': 2000, 'default': 3},
            {'name': 'fastd_matype', 'min': 0, 'max': 8, 'default': 0}],
 'outputs': ['fastk', 'fastd'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None},
           {'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'STOCHRSI',
 'group': 'Momentum Indicators',
 'inputs': ['close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14},
            {'name': 'fastk_period', 'min': 1, 'max': 2000, 'default': 5},
            {'name': 'fastd_period', 'min': 1, 'max': 2000, 'default': 3},
            {'name': 'fastd_matype', 'min': 0, 'max': 8, 'default': 0}],
 'outputs': ['fastk', 'fastd'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None},
           {'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'SUB',
 'group': 'Math Operators',
 'inputs': ['high', 'low'],
 'params': [],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'SUM',
 'group': 'Math Operators',
 'inputs': ['close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'T3',
 'group': 'Overlap Studies',
 'inputs': ['close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 5}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]}
)
