"""IND-2g -- generated TA-Lib catalog snapshot, part 7 of 10.

DO NOT EDIT BY HAND -- regenerate with
`python -m src.core.indicators.catalog.generate_from_talib`. Imports nothing
beyond the stdlib so it loads without TA-Lib installed (snapshot-only
verification, see `generate_from_talib.py` module docstring).
"""
from __future__ import annotations

TALIB_GENERATED_PART: tuple[dict[str, object], ...] = (
    {'name': 'MIDPRICE',
 'group': 'Overlap Studies',
 'inputs': ['high', 'low'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'MIN',
 'group': 'Math Operators',
 'inputs': ['close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'MININDEX',
 'group': 'Math Operators',
 'inputs': ['close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
 'outputs': ['integer'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'MINMAX',
 'group': 'Math Operators',
 'inputs': ['close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
 'outputs': ['min', 'max'],
 'plots': [{'kind': 'line',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None},
           {'kind': 'line',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'MINMAXINDEX',
 'group': 'Math Operators',
 'inputs': ['close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
 'outputs': ['minidx', 'maxidx'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None},
           {'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'MINUS_DI',
 'group': 'Momentum Indicators',
 'inputs': ['high', 'low', 'close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'MINUS_DM',
 'group': 'Momentum Indicators',
 'inputs': ['high', 'low'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'MOM',
 'group': 'Momentum Indicators',
 'inputs': ['close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 10}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'MULT',
 'group': 'Math Operators',
 'inputs': ['high', 'low'],
 'params': [],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'NATR',
 'group': 'Volatility Indicators',
 'inputs': ['high', 'low', 'close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'OBV',
 'group': 'Volume Indicators',
 'inputs': ['close', 'volume'],
 'params': [],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'PLUS_DI',
 'group': 'Momentum Indicators',
 'inputs': ['high', 'low', 'close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'PLUS_DM',
 'group': 'Momentum Indicators',
 'inputs': ['high', 'low'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'PPO',
 'group': 'Momentum Indicators',
 'inputs': ['close'],
 'params': [{'name': 'fastperiod', 'min': 1, 'max': 2000, 'default': 12},
            {'name': 'slowperiod', 'min': 1, 'max': 2000, 'default': 26},
            {'name': 'matype', 'min': 0, 'max': 8, 'default': 0}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'ROC',
 'group': 'Momentum Indicators',
 'inputs': ['close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 10}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'ROCP',
 'group': 'Momentum Indicators',
 'inputs': ['close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 10}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'ROCR',
 'group': 'Momentum Indicators',
 'inputs': ['close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 10}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]}
)
