# loc-allow: IND-2g generated TA-Lib catalog table (161 records) -- deterministic
# rule matrix, ADR-2026-09-10-C Section 7.
"""IND-2g -- generated TA-Lib catalog snapshot. DO NOT EDIT BY HAND.

Regenerate with `python -m src.core.indicators.catalog.generate_from_talib`.
Requires TA-Lib installed -- without it the generator raises
`TALibUnavailableError` instead of silently writing a partial/stale file
(fail-closed). This file itself imports nothing beyond the stdlib so it can be
loaded/validated in environments without the TA-Lib C library (snapshot-only
verification).
"""
from __future__ import annotations

TALIB_GENERATED: tuple[dict[str, object], ...] = (
    {'name': 'ACCBANDS',
     'group': 'Overlap Studies',
     'inputs': ['high', 'low', 'close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 20}],
     'outputs': ['upperband', 'middleband', 'lowerband'],
     'plots': [{'kind': 'band',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': 'lowerband',
                'color_rule': None,
                'precision': None,
                'legend_format': None},
               {'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None},
               {'kind': 'band',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': 'upperband',
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'ACOS',
     'group': 'Math Transform',
     'inputs': ['close'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'AD',
     'group': 'Volume Indicators',
     'inputs': ['high', 'low', 'close', 'volume'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'ADD',
     'group': 'Math Operators',
     'inputs': ['high', 'low'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'ADOSC',
     'group': 'Volume Indicators',
     'inputs': ['high', 'low', 'close', 'volume'],
     'params': [{'name': 'fastperiod', 'min': 1, 'max': 2000, 'default': 3},
                {'name': 'slowperiod', 'min': 1, 'max': 2000, 'default': 10}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'ADX',
     'group': 'Momentum Indicators',
     'inputs': ['high', 'low', 'close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'ADXR',
     'group': 'Momentum Indicators',
     'inputs': ['high', 'low', 'close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'APO',
     'group': 'Momentum Indicators',
     'inputs': ['close'],
     'params': [{'name': 'fastperiod', 'min': 1, 'max': 2000, 'default': 12},
                {'name': 'slowperiod', 'min': 1, 'max': 2000, 'default': 26},
                {'name': 'matype', 'min': 0, 'max': 8, 'default': 0}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'AROON',
     'group': 'Momentum Indicators',
     'inputs': ['high', 'low'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['aroondown', 'aroonup'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None},
               {'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'AROONOSC',
     'group': 'Momentum Indicators',
     'inputs': ['high', 'low'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'ASIN',
     'group': 'Math Transform',
     'inputs': ['close'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'ATAN',
     'group': 'Math Transform',
     'inputs': ['close'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'ATR',
     'group': 'Volatility Indicators',
     'inputs': ['high', 'low', 'close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'AVGDEV',
     'group': 'Price Transform',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'AVGPRICE',
     'group': 'Price Transform',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'BBANDS',
     'group': 'Overlap Studies',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 5},
                {'name': 'matype', 'min': 0, 'max': 8, 'default': 0}],
     'outputs': ['upperband', 'middleband', 'lowerband'],
     'plots': [{'kind': 'band',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': 'lowerband',
                'color_rule': None,
                'precision': None,
                'legend_format': None},
               {'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None},
               {'kind': 'band',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': 'upperband',
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'BETA',
     'group': 'Statistic Functions',
     'inputs': ['high', 'low'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 5}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'BOP',
     'group': 'Momentum Indicators',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CCI',
     'group': 'Momentum Indicators',
     'inputs': ['high', 'low', 'close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDL2CROWS',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDL3BLACKCROWS',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDL3INSIDE',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDL3LINESTRIKE',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDL3OUTSIDE',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDL3STARSINSOUTH',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDL3WHITESOLDIERS',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLABANDONEDBABY',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLADVANCEBLOCK',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLBELTHOLD',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLBREAKAWAY',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLCLOSINGMARUBOZU',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLCONCEALBABYSWALL',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLCOUNTERATTACK',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLDARKCLOUDCOVER',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLDOJI',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLDOJISTAR',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLDRAGONFLYDOJI',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLENGULFING',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLEVENINGDOJISTAR',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLEVENINGSTAR',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLGAPSIDESIDEWHITE',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLGRAVESTONEDOJI',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLHAMMER',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLHANGINGMAN',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLHARAMI',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLHARAMICROSS',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLHIGHWAVE',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLHIKKAKE',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLHIKKAKEMOD',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLHOMINGPIGEON',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLIDENTICAL3CROWS',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLINNECK',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLINVERTEDHAMMER',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLKICKING',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLKICKINGBYLENGTH',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLLADDERBOTTOM',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLLONGLEGGEDDOJI',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLLONGLINE',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLMARUBOZU',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLMATCHINGLOW',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLMATHOLD',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLMORNINGDOJISTAR',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLMORNINGSTAR',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLONNECK',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLPIERCING',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLRICKSHAWMAN',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLRISEFALL3METHODS',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLSEPARATINGLINES',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLSHOOTINGSTAR',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLSHORTLINE',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLSPINNINGTOP',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLSTALLEDPATTERN',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLSTICKSANDWICH',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLTAKURI',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLTASUKIGAP',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLTHRUSTING',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLTRISTAR',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLUNIQUE3RIVER',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLUPSIDEGAP2CROWS',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CDLXSIDEGAP3METHODS',
     'group': 'Pattern Recognition',
     'inputs': ['open', 'high', 'low', 'close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'marker',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CEIL',
     'group': 'Math Transform',
     'inputs': ['close'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CMO',
     'group': 'Momentum Indicators',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'CORREL',
     'group': 'Statistic Functions',
     'inputs': ['high', 'low'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'COS',
     'group': 'Math Transform',
     'inputs': ['close'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'COSH',
     'group': 'Math Transform',
     'inputs': ['close'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'DEMA',
     'group': 'Overlap Studies',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'DIV',
     'group': 'Math Operators',
     'inputs': ['high', 'low'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'DX',
     'group': 'Momentum Indicators',
     'inputs': ['high', 'low', 'close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'EMA',
     'group': 'Overlap Studies',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'EXP',
     'group': 'Math Transform',
     'inputs': ['close'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'FLOOR',
     'group': 'Math Transform',
     'inputs': ['close'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'HT_DCPERIOD',
     'group': 'Cycle Indicators',
     'inputs': ['close'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'HT_DCPHASE',
     'group': 'Cycle Indicators',
     'inputs': ['close'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'HT_PHASOR',
     'group': 'Cycle Indicators',
     'inputs': ['close'],
     'params': [],
     'outputs': ['inphase', 'quadrature'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None},
               {'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'HT_SINE',
     'group': 'Cycle Indicators',
     'inputs': ['close'],
     'params': [],
     'outputs': ['sine', 'leadsine'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None},
               {'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'HT_TRENDLINE',
     'group': 'Overlap Studies',
     'inputs': ['close'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'HT_TRENDMODE',
     'group': 'Cycle Indicators',
     'inputs': ['close'],
     'params': [],
     'outputs': ['integer'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'IMI',
     'group': 'Momentum Indicators',
     'inputs': ['open', 'close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'KAMA',
     'group': 'Overlap Studies',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'LINEARREG',
     'group': 'Statistic Functions',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'LINEARREG_ANGLE',
     'group': 'Statistic Functions',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'LINEARREG_INTERCEPT',
     'group': 'Statistic Functions',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'LINEARREG_SLOPE',
     'group': 'Statistic Functions',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'LN',
     'group': 'Math Transform',
     'inputs': ['close'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'LOG10',
     'group': 'Math Transform',
     'inputs': ['close'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'MA',
     'group': 'Overlap Studies',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30},
                {'name': 'matype', 'min': 0, 'max': 8, 'default': 0}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'MACD',
     'group': 'Momentum Indicators',
     'inputs': ['close'],
     'params': [{'name': 'fastperiod', 'min': 1, 'max': 2000, 'default': 12},
                {'name': 'slowperiod', 'min': 1, 'max': 2000, 'default': 26},
                {'name': 'signalperiod', 'min': 1, 'max': 2000, 'default': 9}],
     'outputs': ['macd', 'macdsignal', 'macdhist'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None},
               {'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None},
               {'kind': 'histogram',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': 'sign',
                'precision': None,
                'legend_format': None}]},
    {'name': 'MACDEXT',
     'group': 'Momentum Indicators',
     'inputs': ['close'],
     'params': [{'name': 'fastperiod', 'min': 1, 'max': 2000, 'default': 12},
                {'name': 'fastmatype', 'min': 0, 'max': 8, 'default': 0},
                {'name': 'slowperiod', 'min': 1, 'max': 2000, 'default': 26},
                {'name': 'slowmatype', 'min': 0, 'max': 8, 'default': 0},
                {'name': 'signalperiod', 'min': 1, 'max': 2000, 'default': 9},
                {'name': 'signalmatype', 'min': 0, 'max': 8, 'default': 0}],
     'outputs': ['macd', 'macdsignal', 'macdhist'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None},
               {'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None},
               {'kind': 'histogram',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': 'sign',
                'precision': None,
                'legend_format': None}]},
    {'name': 'MACDFIX',
     'group': 'Momentum Indicators',
     'inputs': ['close'],
     'params': [{'name': 'signalperiod', 'min': 1, 'max': 2000, 'default': 9}],
     'outputs': ['macd', 'macdsignal', 'macdhist'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None},
               {'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None},
               {'kind': 'histogram',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': 'sign',
                'precision': None,
                'legend_format': None}]},
    {'name': 'MAMA',
     'group': 'Overlap Studies',
     'inputs': ['close'],
     'params': [],
     'outputs': ['mama', 'fama'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None},
               {'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'MAVP',
     'group': 'Overlap Studies',
     'inputs': ['close', 'periods'],
     'params': [{'name': 'minperiod', 'min': 1, 'max': 2000, 'default': 2},
                {'name': 'maxperiod', 'min': 1, 'max': 2000, 'default': 30},
                {'name': 'matype', 'min': 0, 'max': 8, 'default': 0}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'MAX',
     'group': 'Math Operators',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'MAXINDEX',
     'group': 'Math Operators',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
     'outputs': ['integer'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'MEDPRICE',
     'group': 'Price Transform',
     'inputs': ['high', 'low'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'MFI',
     'group': 'Momentum Indicators',
     'inputs': ['high', 'low', 'close', 'volume'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'MIDPOINT',
     'group': 'Overlap Studies',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'MIDPRICE',
     'group': 'Overlap Studies',
     'inputs': ['high', 'low'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'MIN',
     'group': 'Math Operators',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'MININDEX',
     'group': 'Math Operators',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
     'outputs': ['integer'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'MINMAX',
     'group': 'Math Operators',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
     'outputs': ['min', 'max'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None},
               {'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'MINMAXINDEX',
     'group': 'Math Operators',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
     'outputs': ['minidx', 'maxidx'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None},
               {'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'MINUS_DI',
     'group': 'Momentum Indicators',
     'inputs': ['high', 'low', 'close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'MINUS_DM',
     'group': 'Momentum Indicators',
     'inputs': ['high', 'low'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'MOM',
     'group': 'Momentum Indicators',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 10}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'MULT',
     'group': 'Math Operators',
     'inputs': ['high', 'low'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'NATR',
     'group': 'Volatility Indicators',
     'inputs': ['high', 'low', 'close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'OBV',
     'group': 'Volume Indicators',
     'inputs': ['close', 'volume'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'PLUS_DI',
     'group': 'Momentum Indicators',
     'inputs': ['high', 'low', 'close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'PLUS_DM',
     'group': 'Momentum Indicators',
     'inputs': ['high', 'low'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'PPO',
     'group': 'Momentum Indicators',
     'inputs': ['close'],
     'params': [{'name': 'fastperiod', 'min': 1, 'max': 2000, 'default': 12},
                {'name': 'slowperiod', 'min': 1, 'max': 2000, 'default': 26},
                {'name': 'matype', 'min': 0, 'max': 8, 'default': 0}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'ROC',
     'group': 'Momentum Indicators',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 10}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'ROCP',
     'group': 'Momentum Indicators',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 10}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'ROCR',
     'group': 'Momentum Indicators',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 10}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'ROCR100',
     'group': 'Momentum Indicators',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 10}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'RSI',
     'group': 'Momentum Indicators',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'SAR',
     'group': 'Overlap Studies',
     'inputs': ['high', 'low'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'SAREXT',
     'group': 'Overlap Studies',
     'inputs': ['high', 'low'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'SIN',
     'group': 'Math Transform',
     'inputs': ['close'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'SINH',
     'group': 'Math Transform',
     'inputs': ['close'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'SMA',
     'group': 'Overlap Studies',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'SQRT',
     'group': 'Math Transform',
     'inputs': ['close'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'STDDEV',
     'group': 'Statistic Functions',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 5}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'STOCH',
     'group': 'Momentum Indicators',
     'inputs': ['high', 'low', 'close'],
     'params': [{'name': 'fastk_period', 'min': 1, 'max': 2000, 'default': 5},
                {'name': 'slowk_period', 'min': 1, 'max': 2000, 'default': 3},
                {'name': 'slowk_matype', 'min': 0, 'max': 8, 'default': 0},
                {'name': 'slowd_period', 'min': 1, 'max': 2000, 'default': 3},
                {'name': 'slowd_matype', 'min': 0, 'max': 8, 'default': 0}],
     'outputs': ['slowk', 'slowd'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None},
               {'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'STOCHF',
     'group': 'Momentum Indicators',
     'inputs': ['high', 'low', 'close'],
     'params': [{'name': 'fastk_period', 'min': 1, 'max': 2000, 'default': 5},
                {'name': 'fastd_period', 'min': 1, 'max': 2000, 'default': 3},
                {'name': 'fastd_matype', 'min': 0, 'max': 8, 'default': 0}],
     'outputs': ['fastk', 'fastd'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None},
               {'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'STOCHRSI',
     'group': 'Momentum Indicators',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14},
                {'name': 'fastk_period', 'min': 1, 'max': 2000, 'default': 5},
                {'name': 'fastd_period', 'min': 1, 'max': 2000, 'default': 3},
                {'name': 'fastd_matype', 'min': 0, 'max': 8, 'default': 0}],
     'outputs': ['fastk', 'fastd'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None},
               {'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'SUB',
     'group': 'Math Operators',
     'inputs': ['high', 'low'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'SUM',
     'group': 'Math Operators',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'T3',
     'group': 'Overlap Studies',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 5}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'TAN',
     'group': 'Math Transform',
     'inputs': ['close'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'TANH',
     'group': 'Math Transform',
     'inputs': ['close'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'TEMA',
     'group': 'Overlap Studies',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'TRANGE',
     'group': 'Volatility Indicators',
     'inputs': ['high', 'low', 'close'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'TRIMA',
     'group': 'Overlap Studies',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'TRIX',
     'group': 'Momentum Indicators',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'TSF',
     'group': 'Statistic Functions',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'TYPPRICE',
     'group': 'Price Transform',
     'inputs': ['high', 'low', 'close'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'ULTOSC',
     'group': 'Momentum Indicators',
     'inputs': ['high', 'low', 'close'],
     'params': [{'name': 'timeperiod1', 'min': 1, 'max': 2000, 'default': 7},
                {'name': 'timeperiod2', 'min': 1, 'max': 2000, 'default': 14},
                {'name': 'timeperiod3', 'min': 1, 'max': 2000, 'default': 28}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'VAR',
     'group': 'Statistic Functions',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 5}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'WCLPRICE',
     'group': 'Price Transform',
     'inputs': ['high', 'low', 'close'],
     'params': [],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'WILLR',
     'group': 'Momentum Indicators',
     'inputs': ['high', 'low', 'close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'own',
                'default_pane': 'separate',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]},
    {'name': 'WMA',
     'group': 'Overlap Studies',
     'inputs': ['close'],
     'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 30}],
     'outputs': ['real'],
     'plots': [{'kind': 'line',
                'scale': 'overlay',
                'default_pane': 'price',
                'fill_between': None,
                'color_rule': None,
                'precision': None,
                'legend_format': None}]}
)
