"""IND-2g -- generated TA-Lib catalog snapshot, part 0 of 10.

DO NOT EDIT BY HAND -- regenerate with
`python -m src.core.indicators.catalog.generate_from_talib`. Imports nothing
beyond the stdlib so it loads without TA-Lib installed (snapshot-only
verification, see `generate_from_talib.py` module docstring).
"""
from __future__ import annotations

TALIB_GENERATED_PART: tuple[dict[str, object], ...] = (
    {'name': 'ACCBANDS',
 'group': 'Overlap Studies',
 'inputs': ['high', 'low', 'close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 20}],
 'outputs': ['upperband', 'middleband', 'lowerband'],
 'plots': [{'kind': 'band',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': 'lowerband',
            'color_rule': None,
            'precision': None,
            'legend_format': None},
           {'kind': 'line',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None},
           {'kind': 'band',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': 'upperband',
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'ACOS',
 'group': 'Math Transform',
 'inputs': ['close'],
 'params': [],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'AD',
 'group': 'Volume Indicators',
 'inputs': ['high', 'low', 'close', 'volume'],
 'params': [],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'ADD',
 'group': 'Math Operators',
 'inputs': ['high', 'low'],
 'params': [],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'ADOSC',
 'group': 'Volume Indicators',
 'inputs': ['high', 'low', 'close', 'volume'],
 'params': [{'name': 'fastperiod', 'min': 1, 'max': 2000, 'default': 3},
            {'name': 'slowperiod', 'min': 1, 'max': 2000, 'default': 10}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'ADX',
 'group': 'Momentum Indicators',
 'inputs': ['high', 'low', 'close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'ADXR',
 'group': 'Momentum Indicators',
 'inputs': ['high', 'low', 'close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'APO',
 'group': 'Momentum Indicators',
 'inputs': ['close'],
 'params': [{'name': 'fastperiod', 'min': 1, 'max': 2000, 'default': 12},
            {'name': 'slowperiod', 'min': 1, 'max': 2000, 'default': 26},
            {'name': 'matype', 'min': 0, 'max': 8, 'default': 0}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'AROON',
 'group': 'Momentum Indicators',
 'inputs': ['high', 'low'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
 'outputs': ['aroondown', 'aroonup'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None},
           {'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'AROONOSC',
 'group': 'Momentum Indicators',
 'inputs': ['high', 'low'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'ASIN',
 'group': 'Math Transform',
 'inputs': ['close'],
 'params': [],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'ATAN',
 'group': 'Math Transform',
 'inputs': ['close'],
 'params': [],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'ATR',
 'group': 'Volatility Indicators',
 'inputs': ['high', 'low', 'close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'own',
            'default_pane': 'separate',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'AVGDEV',
 'group': 'Price Transform',
 'inputs': ['close'],
 'params': [{'name': 'timeperiod', 'min': 1, 'max': 2000, 'default': 14}],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'AVGPRICE',
 'group': 'Price Transform',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['real'],
 'plots': [{'kind': 'line',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]}
)
