"""IND-2g -- generated TA-Lib catalog snapshot, part 3 of 10.

DO NOT EDIT BY HAND -- regenerate with
`python -m src.core.indicators.catalog.generate_from_talib`. Imports nothing
beyond the stdlib so it loads without TA-Lib installed (snapshot-only
verification, see `generate_from_talib.py` module docstring).
"""
from __future__ import annotations

TALIB_GENERATED_PART: tuple[dict[str, object], ...] = (
    {'name': 'CDLIDENTICAL3CROWS',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLINNECK',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLINVERTEDHAMMER',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLKICKING',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLKICKINGBYLENGTH',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLLADDERBOTTOM',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLLONGLEGGEDDOJI',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLLONGLINE',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLMARUBOZU',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLMATCHINGLOW',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLMATHOLD',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLMORNINGDOJISTAR',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLMORNINGSTAR',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLONNECK',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLPIERCING',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLRICKSHAWMAN',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLRISEFALL3METHODS',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]},
    {'name': 'CDLSEPARATINGLINES',
 'group': 'Pattern Recognition',
 'inputs': ['open', 'high', 'low', 'close'],
 'params': [],
 'outputs': ['integer'],
 'plots': [{'kind': 'marker',
            'scale': 'overlay',
            'default_pane': 'price',
            'fill_between': None,
            'color_rule': None,
            'precision': None,
            'legend_format': None}]}
)
