"""Trust Core contract v1.

Spec: AIOSproject 43_trust_core_identity_consent_suitability_specification_v1.0.md,
73_trust_core_l3_build_and_operational_specification_v1.0.md §4,
107_contract_versioning_and_compatibility_standard_v1.0.md.

The classes in this file are the "contract" — other bounded contexts (after FND-02)
consume this file by importing it and must not reference domain/models.py directly
(106 §5, 71 §4 Contract ownership rule).

On a MAJOR change, do not edit this file; create `contracts/v2.py` instead (107 §3.3).
"""
from __future__ import annotations

from datetime import datetime
from enum import Enum
from uuid import UUID

from pydantic import BaseModel

SCHEMA_VERSION = "v1"


class ConsentState(str, Enum):
    NONE = "NONE"
    ACTIVE = "ACTIVE"
    REVOKED = "REVOKED"


class TenantContext(BaseModel):
    """71 §4 — Do not construct in API body. Only issued by gateway auth
    (`get_current_user`).

    In the P0 scope (personal account), tenant_id == subject_id — 73 §2 "Tenant:
    isolation boundary for personal account, household, or organization"; the
    household/organization (multiple members) scope is covered by a later document
    (66) and this contract does not yet address that extension. That is, the
    `Membership` state machine (grant/suspend/revoke) is not implemented separately
    here — in a state where each tenant has exactly one member there is no target
    to "invite/expel" (per 35 §9.2 principle: "only increase fine-grained file
    splits; module proliferation without contract/owner/test is prohibited").
    """

    tenant_id: UUID
    subject_id: UUID
    role: str = "OWNER"
    mfa_verified: bool
    schema_version: str = SCHEMA_VERSION
    # PLT-28 (107 §3.2 MINOR) — household/organization tenants obtain role via
    # membership rows; attach as optional so those rows are back-referencable.
    # Personal tenant (no membership state machine, see above) remains None.
    # Existing fields are unchanged, so v1 fixtures consumed by this contract pass unmodified.
    membership_id: UUID | None = None


class ConsentDecision(BaseModel):
    """AcceptDisclosure/RevokeConsent command result and the contract consumed
    by other contexts. Does not contain the original disclosure body or user
    answer (73 §8)."""

    consent_id: UUID
    tenant_id: UUID
    purpose: str
    disclosure_id: UUID
    disclosure_revision: int
    state: ConsentState
    accepted_at: datetime | None
    revoked_at: datetime | None
    expires_at: datetime | None
    schema_version: str = SCHEMA_VERSION


class TrustFreshnessDecision(BaseModel):
    """EvaluateTrustFreshness query result — used by consumers such as
    Mandate/Package/Paper Control to verify "does this tenant hold a valid
    consent for this purpose" (73 §4 EvaluateTrustFreshness)."""

    tenant_id: UUID
    purpose: str
    is_fresh: bool
    reason_code: str | None  # 72 §4 error taxonomy, e.g. "POLICY_CONSENT_REVOKED"
    as_of: datetime
    schema_version: str = SCHEMA_VERSION
