"""L4 §2.3(C) — 에러 코드 taxonomy 단일 출처.

Spec: docs/specs/L4_platform_observability_tenancy_api_v1.0.md#§3.3 표

접두 규칙(§2.3): AUTH_/AUTHZ_/VALIDATION_/STATE_/INTEGRITY_/POLICY_/
RISK_/EXCHANGE_/RATE_LIMIT_/INTERNAL_/DEPENDENCY_ 외 금지 —
test_error_codes.py가 이 규칙을 강제한다.
"""
from __future__ import annotations

import enum

from starlette import status


class ErrorCode(str, enum.Enum):
    VALIDATION_INVALID_FIELD = "VALIDATION_INVALID_FIELD"
    VALIDATION_IDEMPOTENCY_KEY_REQUIRED = "VALIDATION_IDEMPOTENCY_KEY_REQUIRED"
    VALIDATION_DISCLOSURE_RETIRED = "VALIDATION_DISCLOSURE_RETIRED"

    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
    AUTH_SESSION_REVOKED = "AUTH_SESSION_REVOKED"
    AUTH_ACCOUNT_LOCKED = "AUTH_ACCOUNT_LOCKED"
    AUTH_MFA_REQUIRED = "AUTH_MFA_REQUIRED"
    AUTH_MFA_INVALID = "AUTH_MFA_INVALID"
    AUTH_TENANT_MISMATCH = "AUTH_TENANT_MISMATCH"

    AUTHZ_FORBIDDEN = "AUTHZ_FORBIDDEN"
    AUTHZ_ZONE_VIOLATION = "AUTHZ_ZONE_VIOLATION"

    POLICY_LIVE_BLOCKED = "POLICY_LIVE_BLOCKED"
    # 표의 "POLICY_*/RISK_*" 행 — 구체 사유는 details.reason_codes에 담고,
    # 코드 자체는 두 도메인의 범용 거부값 하나씩만 둔다(§3.3 "POLICY_*/
    # RISK_* ... details.reason_codes" 참조).
    POLICY_DENIED = "POLICY_DENIED"
    RISK_DENIED = "RISK_DENIED"

    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"

    STATE_CONCURRENCY_CONFLICT = "STATE_CONCURRENCY_CONFLICT"
    STATE_INVALID_TRANSITION = "STATE_INVALID_TRANSITION"

    INTEGRITY_IDEMPOTENCY_CONFLICT = "INTEGRITY_IDEMPOTENCY_CONFLICT"
    # L4 §9 LC-16 — `user_wallets.balance`(레거시 투영)와 원장
    # `USER:*:AVAILABLE` 잔액이 어긋났을 때. 조회 경로는 스스로 봉합하지
    # 않고 이 코드로 명시적으로 실패한다(500 INTERNAL_ERROR와 구분).
    INTEGRITY_WALLET_BALANCE_DRIFT = "INTEGRITY_WALLET_BALANCE_DRIFT"

    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"

    EXCHANGE_UNAVAILABLE = "EXCHANGE_UNAVAILABLE"
    EXCHANGE_FATAL = "EXCHANGE_FATAL"

    DEPENDENCY_NOT_READY = "DEPENDENCY_NOT_READY"

    # LA-24(market_data 읽기 API) — 요청 구간이 저장 커버리지 밖. 0/NaN 채움
    # 금지(§4.1)라 200 빈 배열이 아니라 409로 거부한다. 재시도 불가(수집 후
    # 재요청). 코드명은 시장데이터 스펙 §9.2 LA-24·`ports/provider.py`
    # DataProviderErrorCode와 동일 문자열을 쓴다(단일출처).
    DATA_COVERAGE_MISSING = "DATA_COVERAGE_MISSING"

    INTERNAL_ERROR = "INTERNAL_ERROR"


HTTP_STATUS: dict[ErrorCode, int] = {
    ErrorCode.VALIDATION_INVALID_FIELD: status.HTTP_400_BAD_REQUEST,
    ErrorCode.VALIDATION_IDEMPOTENCY_KEY_REQUIRED: status.HTTP_400_BAD_REQUEST,
    ErrorCode.VALIDATION_DISCLOSURE_RETIRED: status.HTTP_400_BAD_REQUEST,
    ErrorCode.AUTH_REQUIRED: status.HTTP_401_UNAUTHORIZED,
    ErrorCode.AUTH_INVALID_CREDENTIALS: status.HTTP_401_UNAUTHORIZED,
    ErrorCode.AUTH_TOKEN_EXPIRED: status.HTTP_401_UNAUTHORIZED,
    ErrorCode.AUTH_TOKEN_INVALID: status.HTTP_401_UNAUTHORIZED,
    ErrorCode.AUTH_SESSION_REVOKED: status.HTTP_401_UNAUTHORIZED,
    ErrorCode.AUTH_ACCOUNT_LOCKED: status.HTTP_423_LOCKED,
    ErrorCode.AUTH_MFA_REQUIRED: status.HTTP_403_FORBIDDEN,
    ErrorCode.AUTH_MFA_INVALID: status.HTTP_400_BAD_REQUEST,
    ErrorCode.AUTH_TENANT_MISMATCH: status.HTTP_403_FORBIDDEN,
    ErrorCode.AUTHZ_FORBIDDEN: status.HTTP_403_FORBIDDEN,
    ErrorCode.AUTHZ_ZONE_VIOLATION: status.HTTP_403_FORBIDDEN,
    ErrorCode.POLICY_LIVE_BLOCKED: status.HTTP_403_FORBIDDEN,
    ErrorCode.POLICY_DENIED: status.HTTP_403_FORBIDDEN,
    ErrorCode.RISK_DENIED: status.HTTP_403_FORBIDDEN,
    ErrorCode.RESOURCE_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.STATE_CONCURRENCY_CONFLICT: status.HTTP_409_CONFLICT,
    ErrorCode.STATE_INVALID_TRANSITION: status.HTTP_409_CONFLICT,
    ErrorCode.INTEGRITY_IDEMPOTENCY_CONFLICT: status.HTTP_409_CONFLICT,
    ErrorCode.INTEGRITY_WALLET_BALANCE_DRIFT: status.HTTP_409_CONFLICT,
    ErrorCode.RATE_LIMIT_EXCEEDED: status.HTTP_429_TOO_MANY_REQUESTS,
    ErrorCode.EXCHANGE_UNAVAILABLE: status.HTTP_503_SERVICE_UNAVAILABLE,
    ErrorCode.EXCHANGE_FATAL: status.HTTP_502_BAD_GATEWAY,
    ErrorCode.DEPENDENCY_NOT_READY: status.HTTP_503_SERVICE_UNAVAILABLE,
    ErrorCode.DATA_COVERAGE_MISSING: status.HTTP_409_CONFLICT,
    ErrorCode.INTERNAL_ERROR: status.HTTP_500_INTERNAL_SERVER_ERROR,
}

# §3.3 "재시도" 열이 단순 예/아니오가 아닌 코드는 주석으로 남긴다.
# AUTH_TOKEN_EXPIRED — "expired만 refresh": 무조건 재시도가 아니라
# 토큰 갱신 후 재시도라 여기 포함하되, 호출자는 재시도 전 refresh를
# 먼저 해야 한다(RETRYABLE만 보고 그냥 같은 요청을 반복하면 안 됨).
RETRYABLE: frozenset[ErrorCode] = frozenset(
    {
        ErrorCode.AUTH_TOKEN_EXPIRED,
        ErrorCode.AUTH_ACCOUNT_LOCKED,
        ErrorCode.STATE_CONCURRENCY_CONFLICT,
        ErrorCode.RATE_LIMIT_EXCEEDED,
        ErrorCode.EXCHANGE_UNAVAILABLE,
        ErrorCode.DEPENDENCY_NOT_READY,
    }
)
