"""14.2 (backend)/14.5 — Condition combination → FSM compilation (ConditionCompiler).

Spec: 기능설계문서_v1.20.md#FD-14.2 processing steps 1/3/4, 9.11(FSMStrategyConfig), #06 §6.1/6.2

FD-14.2 splits into two branches: "condition combination UI" (frontend) and
"FSM compilation" (pure logic). This session is backend-only, so the UI is
out of scope, but the compilation logic itself is a pure function that can be
fully implemented and tested without the UI — filled in here
(16_backend_signatures.md already scheduled ConditionCompiler as a separate class).

Simplified to 3 inputs for the user: "entry/liquidation/stop-loss conditions",
internally auto-converted to FSM 6 states and transitions:

    IDLE --entry--> BUY_ORDER_PENDING --ORDER_FILLED--> HOLDING
    HOLDING --exit--> SELL_ORDER_PENDING --ORDER_FILLED--> IDLE
    HOLDING --stop_loss--> STOP_LOSS --ORDER_FILLED--> IDLE

ORDER_FILLED is a reserved literal representing a system event (order fill),
not a condition the user creates — its semantic interpretation belongs to the
FROZEN Strategy Engine (FD-4/FD-8), and this compiler only arranges strings.
EMERGENCY_EXIT is not generated by this compiler — it is a state forced by
external safety mechanisms such as Watchdog, not a target of user condition
combinations.

This fixed 6-state/6-transition structure itself cannot produce contradictions,
so "compilation failure due to contradictory state transitions" mentioned in
FD-14.2 narrows to "required condition group is empty" for this simple compiler
(rather than a generic condition builder that creates arbitrary graphs).
"""
from __future__ import annotations

from src.data.models.strategy_fsm import FSMState, FSMStrategyConfig, FSMTransition
from src.services.preview_service import PreviewCondition

ORDER_FILLED = "ORDER_FILLED"

# #06 §6.2 Draft — final list to be confirmed at actual implementation,
# but enforce these 5 as the system-wide whitelist for now (different symbol
# sets per user are out of Phase 1 scope, §6.1).
TARGET_ASSET_WHITELIST = frozenset({"BTC/USDT", "ETH/USDT", "SOL/USDT", "XRP/USDT", "DOGE/USDT"})

_OPERATOR_SYMBOLS = {
    ">": ">",
    "<": "<",
    ">=": ">=",
    "<=": "<=",
    "==": "==",
    "crosses_above": "CROSSES_ABOVE",
    "crosses_below": "CROSSES_BELOW",
}


class ConditionCompileError(Exception):
    """FD-14.2 exception — compilation failure or asset outside whitelist.
    Router converts to 400."""


def _compile_condition_group(conditions: list[PreviewCondition], combine: str) -> str:
    if not conditions:
        raise ConditionCompileError("조건이 최소 1개 이상 필요합니다.")
    if combine not in ("AND", "OR"):
        raise ConditionCompileError(f"지원하지 않는 결합 방식입니다: {combine}")

    parts = []
    for condition in conditions:
        if condition.operator not in _OPERATOR_SYMBOLS:
            raise ConditionCompileError(f"지원하지 않는 연산자입니다: {condition.operator}")
        params_suffix = "".join(
            f"_{key}{value}" for key, value in sorted(condition.params.items())
        )
        symbol = _OPERATOR_SYMBOLS[condition.operator]
        parts.append(f"{condition.indicator}{params_suffix} {symbol} {condition.threshold}")

    joiner = " AND " if combine == "AND" else " OR "
    return joiner.join(parts)


class ConditionCompiler:
    def compile(
        self,
        *,
        strategy_id: str,
        version: str,
        target_asset: str,
        market: str,
        exchange: str,
        author_agent: str,
        entry_conditions: list[PreviewCondition],
        exit_conditions: list[PreviewCondition],
        stop_loss_conditions: list[PreviewCondition],
        entry_combine: str = "AND",
        exit_combine: str = "AND",
        stop_loss_combine: str = "AND",
    ) -> FSMStrategyConfig:
        if target_asset not in TARGET_ASSET_WHITELIST:
            raise ConditionCompileError(
                f"화이트리스트에 없는 target_asset입니다: {target_asset}"
            )

        entry_expr = _compile_condition_group(entry_conditions, entry_combine)
        exit_expr = _compile_condition_group(exit_conditions, exit_combine)
        stop_loss_expr = _compile_condition_group(stop_loss_conditions, stop_loss_combine)

        return FSMStrategyConfig(
            strategy_id=strategy_id,
            version=version,
            target_asset=target_asset,
            market=market,
            exchange=exchange,
            initial_state=FSMState.IDLE,
            states=[
                FSMState.IDLE,
                FSMState.BUY_ORDER_PENDING,
                FSMState.HOLDING,
                FSMState.SELL_ORDER_PENDING,
                FSMState.STOP_LOSS,
                FSMState.EMERGENCY_EXIT,
            ],
            transitions=[
                FSMTransition(
                    from_state=FSMState.IDLE,
                    to_state=FSMState.BUY_ORDER_PENDING,
                    condition=entry_expr,
                ),
                FSMTransition(
                    from_state=FSMState.BUY_ORDER_PENDING,
                    to_state=FSMState.HOLDING,
                    condition=ORDER_FILLED,
                ),
                FSMTransition(
                    from_state=FSMState.HOLDING,
                    to_state=FSMState.SELL_ORDER_PENDING,
                    condition=exit_expr,
                ),
                FSMTransition(
                    from_state=FSMState.HOLDING,
                    to_state=FSMState.STOP_LOSS,
                    condition=stop_loss_expr,
                ),
                FSMTransition(
                    from_state=FSMState.SELL_ORDER_PENDING,
                    to_state=FSMState.IDLE,
                    condition=ORDER_FILLED,
                ),
                FSMTransition(
                    from_state=FSMState.STOP_LOSS,
                    to_state=FSMState.IDLE,
                    condition=ORDER_FILLED,
                ),
            ],
            author_agent=author_agent,
        )
