"""6.9 — KISAdapter.__init__ + OAuth 인증.

Spec: 02_exchange_adapter_v1.2.md#§2.1

편차: 02번 스펙 원문 시그니처는 __init__(app_key, app_secret,
is_paper_trading)였으나, 실제로는 모든 계좌/주문 API가 종합계좌번호(CANO)와
계좌상품코드(ACNT_PRDT_CD)를 필수 파라미터로 요구한다는 것을 조사 중
발견 — 생성자에 cano/acnt_prdt_cd 추가.

L4-21 — OAuth2 token issuance/caching plus the common signing/transport
logic were split out into `oauth_client.py` (`_KISTokenTransportMixin`)
because of the 300-line cap (see that module's docstring for
endpoint/auth details). Only `_resolve_tr_id`/`_PAPER_SWAP_PREFIXES` stay
here — the mutation test in `test_overseas_futureoption_tr_reference.py`
monkeypatches `_PAPER_SWAP_PREFIXES` directly on this module
(`adapter_module`) at global scope (see oauth_client.py's module docstring).
"""
from __future__ import annotations

from decimal import Decimal

from src.data.models.base import AssetClass
from src.data.models.trading import Order
from src.exchanges.common.adapter import ExchangeAdapter
from src.exchanges.common.live_guard import require_paper_sandbox
from src.exchanges.common.types import ExchangeCapability, MarketHours
from src.exchanges.kis.account_mixin import KISAccountMixin
from src.exchanges.kis.domestic_bond_mixin import KISDomesticBondMixin
from src.exchanges.kis.domestic_futureoption_mixin import KISDomesticFutureoptionMixin
from src.exchanges.kis.domestic_stock_extra_mixin import KISDomesticStockExtraMixin
from src.exchanges.kis.elw_mixin import KISElwMixin
from src.exchanges.kis.etf_mixin import KISEtfMixin
from src.exchanges.kis.generated import KISGeneratedMixin
from src.exchanges.kis.market_data_mixin import KISMarketDataMixin
from src.exchanges.kis.oauth_client import PAPER_BASE_URL, REAL_BASE_URL, _KISTokenTransportMixin
from src.exchanges.kis.order_dispatch import dispatch_place_order
from src.exchanges.kis.overseas_futureoption_mixin import KISOverseasFutureoptionMixin
from src.exchanges.kis.overseas_stock_mixin import KISOverseasStockMixin
from src.exchanges.kis.trading_mixin import KISTradingMixin
from src.exchanges.kis.trading_query_mixin import KISTradingQueryMixin
from src.exchanges.kis.websocket_mixin import KISWebSocketMixin

# tests/contract/exchanges/kis/test_generated_contract.py imports these
# names — re-exported as-is from oauth_client.py (not a duplicate definition).
__all__ = ["PAPER_BASE_URL", "REAL_BASE_URL", "KISAdapter", "_KISHTTPClient"]

# 앞글자가 이 중 하나면 모의투자 tr_id는 'V'로 치환한다(실거래/정정취소류).
# 시세조회(F로 시작 등)는 치환 대상 아님 — 실전/모의 동일 tr_id 사용.
_PAPER_SWAP_PREFIXES = ("T", "J", "C")


class _KISHTTPClient(_KISTokenTransportMixin):
    """tr_id live/paper substitution. See `_KISTokenTransportMixin`
    (oauth_client.py) for token issuance/transport."""

    def _resolve_tr_id(self, tr_id: str) -> str:
        if self._is_paper_trading and tr_id[0] in _PAPER_SWAP_PREFIXES:
            return "V" + tr_id[1:]
        return tr_id


class KISAdapter(
    _KISHTTPClient,
    KISMarketDataMixin,
    KISAccountMixin,
    KISTradingMixin,
    KISTradingQueryMixin,
    KISDomesticStockExtraMixin,
    KISOverseasStockMixin,
    KISDomesticBondMixin,
    KISDomesticFutureoptionMixin,
    KISOverseasFutureoptionMixin,
    KISElwMixin,
    KISEtfMixin,
    KISWebSocketMixin,
    KISGeneratedMixin,
    ExchangeAdapter,
):
    """한국투자증권(KIS) — 국내 REST+WebSocket 공식 API, OAuth 2.0 인증.

    `KISGeneratedMixin` (BR-12, ADR-2026-09-06-I D7) — a bundle of methods
    machine-generated by `scripts/kis_generate_adapters.py` from the
    baseline list (BR-11) for the 289 not-yet-started TRs. Guarantees only
    request assembly (method/path/tr_id/params) and returns the response
    unparsed, raw — the polishing that converts it into domain types, like
    the mixins above, is the job of a review leaf (BR-13~15) once a real
    account is available.

    ⚠️ 검증 필요 가정(09번 §9.1 #8과 동일 원칙) — Order.client_order_id를
    영속적 멱등성 키로 가정한 01번 설계와 달리, KIS는 주문 시 자체 채번한
    ODNO(주문번호)를 반환하며 client_order_id 개념 자체가 없다 — 이
    Adapter는 client_order_id를 KIS에 전달하지 않는다(전달할 방법이 없음).
    """

    @property
    def is_paper_trading(self) -> bool:
        return self._is_paper_trading

    @property
    def is_sandboxed(self) -> bool:
        """레드팀 감사(2026-09-01-08) — 생성자의 is_paper_trading 그대로 노출."""
        return self._is_paper_trading

    def get_capabilities(self) -> ExchangeCapability:
        """BR-8(ADR-2026-09-06-I D2, ADR-H D7) — v1.4(ADR-2026-08-28)는
        Phase 1 스콥 논리로 KR_EQUITY만 선언했으나, 그 뒤 BR-3~7이 국내주식
        조회 전수·해외주식 거래소 전수·해외 실시간 웹소켓·국내/해외
        선물옵션을 이미 구현했다 — capabilities가 갱신되지 않아 Validator
        (`validate_order_params`)와 OMS(`assert_supported`)가 전부 "미지원"
        으로 거부하는 결함이 있었다(§10 BR). 실제 구현 상태와 선언을 여기서
        일치시킨다 — 아래 매트릭스는 각 자산군을 처리하는 코드 위치다:
          - KR_EQUITY/KR_ETF/KR_ETN: trading_mixin.place_order (도메스틱
            order-cash, ETF/ETN도 KRX 종목코드라 같은 엔드포인트 재사용)
          - KR_FUTURES/KR_OPTION: domestic_futureoption_mixin(BR-6)
          - US_EQUITY/US_ETF/US_ETN: overseas_stock_mixin(BR-4, 9개 거래소)
          - OVERSEAS_FUTURES/OVERSEAS_OPTION: overseas_futureoption_mixin(BR-7)
        이 클래스의 `place_order()`가 위 매핑대로 실제 분기한다(아래 참조) —
        capabilities만 넓히고 분기를 빼먹으면 다른 자산군 주문이 조용히
        domestic_stock 엔드포인트로 잘못 나갈 뻔했던 결함이 이 리프의 핵심
        수정이다.

        범위 밖(AssetClass enum 미존재) — domestic_bond_mixin(채권)과
        elw_mixin(ELW)도 실제로 구현돼 있지만 `AssetClass`에 대응 값이
        없어(src/data/models/base.py) `Order.asset_class`로 표현할 방법이
        구조적으로 없다 — enum 확장은 이 리프의 파일 스콥(trading.py/
        base.py 제외) 밖이라 후속 리프가 필요하다. CRYPTO는 KIS가 다루지
        않는 자산군이라 제외한다."""
        return ExchangeCapability(
            exchange_name="kis",
            supported_asset_classes=[
                AssetClass.KR_EQUITY,
                AssetClass.KR_ETF,
                AssetClass.KR_ETN,
                AssetClass.KR_FUTURES,
                AssetClass.KR_OPTION,
                AssetClass.US_EQUITY,
                AssetClass.US_ETF,
                AssetClass.US_ETN,
                AssetClass.OVERSEAS_FUTURES,
                AssetClass.OVERSEAS_OPTION,
            ],
            supports_spot=True,
            supports_futures=True,
            supports_options=True,
            # 증거금 레버리지 배율은 미검증(실계좌 확보 전까지 조사 못함) —
            # 과장 대신 보수적 기본값을 유지한다(8.3 원칙). 이 값을 소비하는
            # 다운스트림 리스크 로직은 현재 없음(grep 확인, 2026-09-07).
            supports_leverage=False,
            # 02d 스펙 §6 — 승인키 인증 확인 후 실시간 체결가/호가/체결통보
            # 구현됨(websocket_mixin.py). 체결통보 채널(암호화)은 다른 두
            # 채널보다 신뢰도가 낮음(모듈 docstring 참조) — 그래도 API
            # 연동 자체는 존재하므로 True로 선언한다.
            supports_websocket=True,
            max_leverage=Decimal("1"),
            reference_feed_coverage="high",
            has_official_sandbox=True,
            # 국내 정규장 기준 대표값 — 이 필드는 거래소당 1개라 해외 심볼
            # (US_EQUITY 등)의 실제 개장시간은 여기 표현되지 않는다(심볼별
            # 캘린더는 foundation/market_data/domain/calendar 몫, 스콥 밖).
            market_hours=MarketHours(
                timezone="Asia/Seoul",
                open_time="09:00",
                close_time="15:30",
                trading_days=["MON", "TUE", "WED", "THU", "FRI"],
            ),
        )

    @require_paper_sandbox
    async def place_order(self, order: Order) -> Order:
        """BR-8 계약 승격 — `order.asset_class`로 실제 KIS 엔드포인트를
        분기한다(order_dispatch.py). 이전에는 `KISTradingMixin.place_order`
        (domestic_stock 전용)가 그대로 ABC 계약을 채워, get_capabilities()
        만 넓히면 해외주식·선물옵션 Order가 조용히 국내주식 파라미터로
        잘못된 시장에 나갈 뻔했다 — 이 리프의 핵심 수정.

        cancel_order/modify_order/get_order는 이 리프에서 확장하지 않는다 —
        `order_id: str` 하나만 받는 ABC 시그니처로는 asset_class를 알 수
        없고(주문 시점의 Order와 달리 opaque id뿐), 선물옵션 취소는
        quantity가 필수 키워드라(cancel_futureoption_order) 시그니처
        자체가 다르다 — 비-도메스틱 자산군의 취소/정정/조회는 당분간 각
        mixin의 전용 메서드(cancel_futureoption_order 등)를 호출부가
        직접 써야 한다."""
        return await dispatch_place_order(self, order)
