"""Specification leaf traceability and template requirements -- task-10846, CONSIST-1.

Tests stay grouped by the consistency checker responsibility.
Patch spec_trace globals at their defining module, not the CLI re-exports.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from types import ModuleType

import pytest

from scripts.consistency import spec_trace

ROOT = Path(__file__).resolve().parents[3]
SCRIPTS_DIR = ROOT / "scripts"


def _load_module(name: str, path: Path) -> ModuleType:
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


cc = _load_module("check_consistency", SCRIPTS_DIR / "check_consistency.py")


def _write(tmp_path: Path, relative: str, content: str) -> Path:
    path = tmp_path / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path



# ---------------------------------------------------------------------------
# 8. spec_leaf_untraced
# ---------------------------------------------------------------------------


def test_spec_leaf_flags_untraced_id(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "docs/specs/L4_x_v1.0.md",
        "## 9. 리프 목록\n| 리프 ID | 파일 |\n|---|---|\n| Z-99 | src/z.py |\n",
    )
    hits = cc.check_spec_leaf_traceability(tmp_path)
    assert hits == [("docs/specs#Z-99", 0)]


def test_spec_leaf_passes_when_referenced_in_code(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "docs/specs/L4_x_v1.0.md",
        "## 9. 리프 목록\n| 리프 ID | 파일 |\n|---|---|\n| Z-99 | src/z.py |\n",
    )
    _write(tmp_path, "src/z.py", "# Z-99 구현\nx = 1\n")
    assert cc.check_spec_leaf_traceability(tmp_path) == []


def test_spec_leaf_expands_range_tokens(tmp_path: Path) -> None:
    assert cc._expand_leaf_ids("R-05~R-07") == ["R-05", "R-06", "R-07"]


def test_collect_spec_leaf_ids_ignores_rows_inside_status_block(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "docs/specs/L4_x_v1.0.md",
        "## 9. 리프 목록\n| 리프 ID | 파일 |\n|---|---|\n| EO-01 | src/eo.py |\n\n"
        "## 11. 진행 현황 (자동 생성)\n\n"
        "<!-- spec-status:begin (auto-generated by C:/aios/pm/spec_status.py -- do not edit) -->\n"
        "| ID | 리프 | 상태 | commit |\n|---|---|---|---|\n"
        "| EO-1 | src/eo.py | done | abc123 |\n"
        "<!-- spec-status:end -->\n",
    )
    ids = cc._collect_spec_leaf_ids(tmp_path / "docs" / "specs")
    assert ids == {"EO-01"}


def test_spec_leaf_flags_id_that_is_prefix_of_another_traced_id(tmp_path: Path) -> None:
    # task-3680: substring 매칭("AI-2 in code_blob")은 AI-2가 AI-22의 접두라서
    # AI-22만 구현된 코드를 보고도 AI-2를 "추적됨"으로 오판했다(esc-ci-6e80c35b1015).
    _write(
        tmp_path,
        "docs/specs/L4_x_v1.0.md",
        "## 9. 리프 목록\n| 리프 ID | 파일 |\n|---|---|\n"
        "| Z-1 | src/z1.py |\n| Z-10 | src/z10.py |\n",
    )
    _write(tmp_path, "src/z10.py", "# Z-10 구현\nx = 1\n")
    hits = cc.check_spec_leaf_traceability(tmp_path)
    assert hits == [("docs/specs#Z-1", 0)]


def test_spec_leaf_flags_id_that_is_prefix_of_id_in_commit_subject(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _write(
        tmp_path,
        "docs/specs/L4_x_v1.0.md",
        "## 9. 리프 목록\n| 리프 ID | 파일 |\n|---|---|\n| AI-2 | src/token.py |\n",
    )
    monkeypatch.setattr(
        spec_trace, "_git_commit_subjects", lambda root: "feat: task-2657 AI-22 AiStudioPage\n"
    )
    hits = cc.check_spec_leaf_traceability(tmp_path)
    assert hits == [("docs/specs#AI-2", 0)]


def test_spec_leaf_passes_when_id_appears_as_whole_token_in_commit_subject(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _write(
        tmp_path,
        "docs/specs/L4_x_v1.0.md",
        "## 9. 리프 목록\n| 리프 ID | 파일 |\n|---|---|\n| AI-2 | src/token.py |\n",
    )
    monkeypatch.setattr(
        spec_trace, "_git_commit_subjects", lambda root: "feat: task-2600 AI-2 token_rules.py\n"
    )
    assert cc.check_spec_leaf_traceability(tmp_path) == []


def test_spec_leaf_passes_when_status_block_duplicates_unpadded_id(tmp_path: Path) -> None:
    # task-3629 CONSIST-1: spec_status.py의 자동생성 §11 표는 norm_leaf_id로 선행 0을
    # 뗀 ID를 쓴다(EO-1). §9는 패딩형(EO-01)이라 코드/커밋 검색엔 EO-01만 등장하므로,
    # 이 블록을 리프로 잘못 집계하면 EO-1이 미추적으로 오탐된다.
    _write(
        tmp_path,
        "docs/specs/L4_x_v1.0.md",
        "## 9. 리프 목록\n| 리프 ID | 파일 |\n|---|---|\n| EO-01 | src/eo.py |\n\n"
        "## 11. 진행 현황 (자동 생성)\n\n"
        "<!-- spec-status:begin (auto-generated by C:/aios/pm/spec_status.py -- do not edit) -->\n"
        "| ID | 리프 | 상태 | commit |\n|---|---|---|---|\n"
        "| EO-1 | src/eo.py | done | abc123 |\n"
        "<!-- spec-status:end -->\n",
    )
    _write(tmp_path, "src/eo.py", "# EO-01 구현\nx = 1\n")
    assert cc.check_spec_leaf_traceability(tmp_path) == []


def test_git_grep_leaf_candidate_lines_returns_none_outside_git_repo(tmp_path: Path) -> None:
    # task-8949: `tmp_path`는 git 저장소가 아니다 -- `tests/`가 실존해야 git
    # 호출까지 도달하고, 거기서 128(not a git repository)로 실패해야 한다.
    # 그 실패는 spec_leaf_untraced가 조용히 삼켜 예전 rglob 경로로 후퇴한다
    # (아래 fallback 테스트가 그 경로를 검증한다).
    _write(tmp_path, "tests/test_z.py", "x = 1\n")
    assert spec_trace._git_grep_leaf_candidate_lines(tmp_path, ("tests", "scripts")) is None


def test_spec_leaf_falls_back_to_full_scan_when_git_grep_unavailable(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    # git grep이 실패해도(비-git 디렉터리, git 미설치 등) 결과가 달라지면 안
    # 된다 -- fallback 경로가 여전히 tests/의 파일을 직접 읽어 참조를 찾는다.
    monkeypatch.setattr(spec_trace, "_git_grep_leaf_candidate_lines", lambda root, subdirs: None)
    _write(
        tmp_path,
        "docs/specs/L4_x_v1.0.md",
        "## 9. 리프 목록\n| 리프 ID | 파일 |\n|---|---|\n| Z-99 | tests/test_z.py |\n",
    )
    _write(tmp_path, "tests/test_z.py", "# Z-99 회귀 테스트\nx = 1\n")
    assert cc.check_spec_leaf_traceability(tmp_path) == []


def test_spec_leaf_finds_reference_via_git_grep_in_tests_dir(tmp_path: Path) -> None:
    # git-grep 경로 자체를 실제 git 저장소에서 검증한다 -- tmp_path가 git repo가
    # 아니면 위 fallback 경로만 타므로, 이 테스트에서만 별도로 `git init`한다.
    import subprocess

    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    _write(
        tmp_path,
        "docs/specs/L4_x_v1.0.md",
        "## 9. 리프 목록\n| 리프 ID | 파일 |\n|---|---|\n| Z-99 | tests/test_z.py |\n",
    )
    _write(tmp_path, "tests/test_z.py", "# Z-99 회귀 테스트\nx = 1\n")
    subprocess.run(["git", "add", "tests/test_z.py"], cwd=tmp_path, check=True)
    lines = spec_trace._git_grep_leaf_candidate_lines(tmp_path, ("tests", "scripts"))
    assert lines is not None
    assert "Z-99" in lines
    assert cc.check_spec_leaf_traceability(tmp_path) == []


def test_spec_leaf_still_flags_untraced_id_with_real_git_repo(tmp_path: Path) -> None:
    # git-grep 경로에서도 "아무 데도 없으면 미추적으로 남는다"는 판정 자체는
    # 그대로다 -- 후보 줄만 골라올 뿐 판정 로직은 바꾸지 않았다.
    import subprocess

    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    _write(
        tmp_path,
        "docs/specs/L4_x_v1.0.md",
        "## 9. 리프 목록\n| 리프 ID | 파일 |\n|---|---|\n| Z-99 | tests/test_z.py |\n",
    )
    _write(tmp_path, "tests/test_other.py", "# 무관한 파일\nx = 1\n")
    subprocess.run(["git", "add", "tests/test_other.py"], cwd=tmp_path, check=True)
    hits = cc.check_spec_leaf_traceability(tmp_path)
    assert hits == [("docs/specs#Z-99", 0)]


# ---------------------------------------------------------------------------
# 12. spec_template_incomplete
# ---------------------------------------------------------------------------


def test_spec_template_flags_missing_sections(tmp_path: Path) -> None:
    _write(tmp_path, "docs/specs/L4_x_v1.0.md", "# 명세\n내용만 있고 절 구분이 없다.\n")
    hits = cc.check_spec_template(tmp_path)
    assert ("docs/specs/L4_x_v1.0.md", 0) in hits


def test_spec_template_passes_with_required_sections(tmp_path: Path) -> None:
    _write(
        tmp_path,
        "docs/specs/L4_x_v1.0.md",
        "# 명세\n## 9. 리프 목록\n표\n## 10. 미확정·리스크\n없음\n",
    )
    assert cc.check_spec_template(tmp_path) == []
