"""Charting contracts v1 — `charting-v1`.

Spec: docs/specs/L4_analytics_authoring_backtest_marketplace_v1.0.md §2.2,
§9.6 CH-5, 107_contract_versioning_and_compatibility_standard_v1.0.md.

`DrawingsDocumentView.drawings` maintains a 1:1 element-level mapping with
`DrawingsDocument.drawings` in CH-4 `serialize.ts`(8bd4077) — carried as raw
`dict` without re-modelling via Pydantic discriminated unions (the shape's
fidelity is verified by `domain/rules.py` in a fail-closed manner, so no
dual schema is introduced).

On MAJOR changes, do not edit this file — create `contracts/v2.py` instead
(107-bugbust §3.3).
"""

from __future__ import annotations

from datetime import datetime
from typing import Any
from uuid import UUID

from pydantic import BaseModel, Field, model_validator

SCHEMA_VERSION = "v1"


class ChartLayoutView(BaseModel):
    id: UUID
    tenant_id: UUID
    owner_subject_id: UUID
    name: str
    layout_state: dict[str, Any]
    revision: int
    created_at: datetime
    updated_at: datetime
    schema_version: str = SCHEMA_VERSION


class CreateChartLayoutRequest(BaseModel):
    name: str = Field(min_length=1, max_length=120)
    layout_state: dict[str, Any] = Field(default_factory=dict)


class ChartIndicatorTemplateView(BaseModel):
    """`template` is CH-17a `templateModel.ts`'s `Template`
    (`encodeTemplate()` output) as-is — this contract does not remodel its
    internals either (same principle as `layout_state`, see the file's
    top-level docstring)."""

    id: UUID
    tenant_id: UUID
    owner_subject_id: UUID
    name: str
    template: dict[str, Any]
    revision: int
    created_at: datetime
    updated_at: datetime
    schema_version: str = SCHEMA_VERSION


class CreateChartIndicatorTemplateRequest(BaseModel):
    name: str = Field(min_length=1, max_length=120)
    template: dict[str, Any]


class UpdateChartLayoutRequest(BaseModel):
    """Partial update — at least one of `name` or `layout_state` must be provided."""

    expected_revision: int
    name: str | None = Field(default=None, min_length=1, max_length=120)
    layout_state: dict[str, Any] | None = None

    @model_validator(mode="after")
    def _require_at_least_one_field(self) -> UpdateChartLayoutRequest:
        if self.name is None and self.layout_state is None:
            raise ValueError("name 또는 layout_state 중 최소 하나는 있어야 합니다.")
        return self


class DrawingsDocumentView(BaseModel):
    """1:1 with CH-4 `DrawingsDocument` — `schema_version`(int, version of the
    drawings document itself, a separate concept from this contract file's
    `SCHEMA_VERSION`(str)) + `drawings`. `revision` is an extra field for
    optimistic locking (not in CH-4, MINOR extension)."""

    layout_id: UUID
    schema_version: int
    drawings: list[dict[str, Any]]
    revision: int
    updated_at: datetime


class PutDrawingsRequest(BaseModel):
    expected_revision: int
    schema_version: int
    drawings: list[dict[str, Any]]
