"""Public symmetric-key encryption utility (AES-256-GCM).

Spec: docs/specs/L4_platform_observability_tenancy_api_v1.0.md#§9 PLT-31
(+ §2 line 101). Format with key version (kid): `aios1$<kid>$<b64(nonce+ct)>` — AAD is
the kid. Tokens without the prefix are treated as legacy (produced by `legacy_encrypt`);
decrypt with `kid="legacy"` and no AAD (must match the original generation method so the
authentication tag verifies).

FD-11.2 (MFA secret), FD-12.1 (exchange credentials), and FD-11.5 (withdrawal whitelist
destinations) all reuse the same single application-level key (principle in §7.3 of spec
07) — centralise encryption logic here so each caller does not reimplement it.

The original `encrypt(plaintext, key: str)` / `decrypt(token, key: str)` were renamed to
`legacy_encrypt` / `legacy_decrypt` (PLT-31) — persisted ciphertext still uses the format
produced by those two functions, so never change their signatures.
"""
from __future__ import annotations

import base64
import os

from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from src.core.security.key_ring import KeyRing

_NONCE_SIZE = 12  # AES-GCM standard 96-bit nonce
_FORMAT_PREFIX = "aios1"
_LEGACY_KID = "legacy"


def _key_bytes(key: str) -> bytes:
    """CREDENTIAL_ENCRYPTION_KEY is a 64-char hex string generated by
    `openssl rand -hex 32` (per .env.example) — decodes to a 32-byte raw key (AES-256)."""
    raw = bytes.fromhex(key)
    if len(raw) != 32:
        raise ValueError("CREDENTIAL_ENCRYPTION_KEY는 32바이트(hex 64자)여야 합니다.")
    return raw


def legacy_encrypt(plaintext: str, key: str) -> str:
    aesgcm = AESGCM(_key_bytes(key))
    nonce = os.urandom(_NONCE_SIZE)
    ciphertext = aesgcm.encrypt(nonce, plaintext.encode("utf-8"), None)
    return base64.b64encode(nonce + ciphertext).decode("ascii")


def legacy_decrypt(token: str, key: str) -> str:
    raw = base64.b64decode(token)
    nonce, ciphertext = raw[:_NONCE_SIZE], raw[_NONCE_SIZE:]
    aesgcm = AESGCM(_key_bytes(key))
    return aesgcm.decrypt(nonce, ciphertext, None).decode("utf-8")


def encrypt(plaintext: str, ring: KeyRing) -> str:
    """Always writes in the new format `aios1$<kid>$<b64>` (kid=ring.active_kid, AAD=kid)."""
    kid = ring.active_kid
    aad = kid.encode("ascii")
    aesgcm = AESGCM(ring.key(kid))
    nonce = os.urandom(_NONCE_SIZE)
    ciphertext = aesgcm.encrypt(nonce, plaintext.encode("utf-8"), aad)
    body = base64.b64encode(nonce + ciphertext).decode("ascii")
    return f"{_FORMAT_PREFIX}${kid}${body}"


def decrypt(token: str, ring: KeyRing) -> str:
    """Decrypt `aios1$<kid>$<b64>` with kid/AAD=kid; prefix-less legacy tokens with
    kid="legacy" / no AAD (same conditions as legacy_encrypt)."""
    if token.startswith(f"{_FORMAT_PREFIX}$"):
        _, kid, body = token.split("$", 2)
        aad = kid.encode("ascii")
    else:
        kid, body = _LEGACY_KID, token
        aad = None
    raw = base64.b64decode(body)
    nonce, ciphertext = raw[:_NONCE_SIZE], raw[_NONCE_SIZE:]
    aesgcm = AESGCM(ring.key(kid))
    return aesgcm.decrypt(nonce, ciphertext, aad).decode("utf-8")


class LocalKeyRingKmsAdapter:
    """`KmsPort` adapter (FA-22) backed by a local, env-var-provisioned `KeyRing`.
    Delegates `encrypt`/`decrypt` to the module-level functions above so the
    on-disk ciphertext format (`aios1$<kid>$<b64>`) and existing round-trip
    behaviour are unchanged — callers going through the port see byte-identical
    results to calling `encrypt`/`decrypt` directly with the same `KeyRing`.

    Lives here (not in `key_ring.py`) so `KeyRing` never needs to import this
    module — `key_ring.py` -> `encryption.py` is the only allowed edge between
    the two (`encryption.py` already imports `KeyRing`; the reverse direction
    would be a cycle even as a function-local import, per `check_import_linter.py`
    `cycles:src`, which scans all `Import`/`ImportFrom` nodes regardless of scope).
    """

    def __init__(self, ring: KeyRing) -> None:
        self._ring = ring

    def get_key(self, kid: str) -> bytes:
        return self._ring.key(kid)

    def encrypt(self, plaintext: str) -> str:
        return encrypt(plaintext, self._ring)

    def decrypt(self, token: str) -> str:
        return decrypt(token, self._ring)

    def rotate(self, new_active_kid: str) -> LocalKeyRingKmsAdapter:
        """Return a new adapter whose active kid is `new_active_kid`. The kid must
        already be present in the ring's key material (see `KeyRing.with_active_kid`)."""
        return LocalKeyRingKmsAdapter(self._ring.with_active_kid(new_active_kid))
