"""BR-12(ADR-2026-09-06-I D7) 한글 TR 레이블 보관 파일 렌더러 -- `kis_generate_adapters.py`
에서 분할됨(CLAUDE.md 파일 정책, 500줄 경고선).

언어 정책(ADR-2026-09-07-A, task-1990): `src/` 아래 주석·독스트링은 영문이어야
하므로 메서드 독스트링 템플릿에서 한글 TR 레이블을 뺐다. 정보 손실을 막기 위해
레이블은 도메인별 `{domain}_tr_labels.py`에 일반 dict 리터럴(독스트링도 주석도
아닌 값)로 옮겨 그대로 보존한다 — 이 값은 `check_code_language.py` 검사 대상이
아니다.
"""
from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path
from types import ModuleType
from typing import Any


def _load_module(name: str, path: Path) -> ModuleType:
    """`sys.modules`에 이미 있으면 재사용한다(`kis_generate_adapters._load_module`과
    동일 이유 -- 클래스 정체성 분열 방지)."""
    existing = sys.modules.get(name)
    if existing is not None:
        return existing
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"모듈 로드 실패: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


_HERE = Path(__file__).resolve().parent
_rendering = _load_module("kis_rendering", _HERE / "kis_rendering.py")
_chunking = _load_module("kis_chunking", _HERE / "kis_chunking.py")
_display_width = _rendering._display_width
KisGenerateError = _rendering.KisGenerateError
_FILE_LINE_CAP = _chunking._FILE_LINE_CAP

_LABEL_LINE_WIDTH_BUDGET = 96  # 단일 줄로 뒀을 때 ruff E501(100, 동아시아 폭 2) 여유
_LABEL_CHUNK_WIDTH = 84  # 줄바꿈 시 각 조각의 표시폭 상한(들여쓰기+따옴표 여유 포함)


def _wrap_literal(text: str, max_width: int) -> list[str]:
    """`text`를 표시폭 기준 `max_width` 이하 조각으로 문자 단위(단어 경계 무시)로
    자른다 -- 인접 문자열 리터럴로 이어 붙이면 원문과 바이트 동일(정보 손실 없음).
    한글 레이블은 데이터라 `_wrap_display`(단어 단위, 줄바꿈에 공백 정보 유실 가능)를
    쓰면 안 된다."""
    chunks: list[str] = []
    current = ""
    current_width = 0
    for ch in text:
        ch_width = _display_width(ch)
        if current and current_width + ch_width > max_width:
            chunks.append(current)
            current, current_width = "", 0
        current += ch
        current_width += ch_width
    if current:
        chunks.append(current)
    return chunks or [text]


def _tr_label_entry(tr_id: str, label: str) -> list[str]:
    key_literal = json.dumps(tr_id, ensure_ascii=False)
    single = f"    {key_literal}: {json.dumps(label, ensure_ascii=False)},"
    if _display_width(single) <= _LABEL_LINE_WIDTH_BUDGET:
        return [single]
    lines = [f"    {key_literal}: ("]
    lines.extend(
        f"        {json.dumps(chunk, ensure_ascii=False)}"
        for chunk in _wrap_literal(label, _LABEL_CHUNK_WIDTH)
    )
    lines.append("    ),")
    return lines


def render_tr_labels_file(
    domain: str, rows: list[dict[str, Any]], *, file_line_cap: int = _FILE_LINE_CAP
) -> str:
    """`domain`의 한글 TR 레이블 보관 파일 -- 독스트링·주석이 아닌 일반 dict
    리터럴이라 `check_code_language.py`(ADR-2026-09-07-A) 검사 대상이 아니다.
    `_summary_line`이 메서드 독스트링 대신 이 파일을 가리킨다(정보 보존)."""
    entries = "\n".join(
        line for row in rows for line in _tr_label_entry(row["tr_id"], row["label"])
    )
    text = "\n".join(
        [
            '"""Auto-generated by BR-12 (ADR-2026-09-06-I D7) -- Korean TR labels for',
            f"{domain}.",
            "",
            "`scripts/kis_generate_adapters.py` generates this from",
            "`docs/design/kis_tr_reference.json` (BR-11) -- do not hand-edit (a regeneration",
            "overwrites it). ADR-2026-09-07-A only requires English comments/docstrings under",
            "`src/`; plain string/dict literals may stay Korean, so the labels live here",
            "instead of in the generated mixins' docstrings.",
            '"""',
            "from __future__ import annotations",
            "",
            "TR_LABELS: dict[str, str] = {",
            entries,
            "}",
            "",
        ]
    )
    if text.count("\n") + 1 > file_line_cap:
        raise KisGenerateError(
            f"{domain} tr_labels: {text.count(chr(10)) + 1}줄 > {file_line_cap}줄 상한"
        )
    return text
