"""BR-12(ADR-2026-09-06-I D7) 메서드 텍스트 렌더러 -- `kis_generate_adapters.py`에서
분할됨(CLAUDE.md 파일 정책, 500줄 경고선).

REST/WS 메서드 하나(행 1개)를 코드 텍스트(줄 리스트)로 렌더링하는 순수 함수만
모은다. 주문성 판정(`is_order_method`)과 언어 정책 가드(`_docstring_lines`)도
여기 있다 -- 둘 다 메서드 렌더링과 같은 변경 축이라 분리하지 않는다.
"""
from __future__ import annotations

import re
import unicodedata
from pathlib import Path
from typing import Any


class KisGenerateError(ValueError):
    """기준 목록 형식 오류 또는 생성 불가능한 행(미지원 HTTP 메서드 등)."""


def _pascal(domain: str) -> str:
    return "".join(part.capitalize() for part in domain.split("_"))


def _method_name(row: dict[str, Any]) -> str:
    stem = Path(row["source_path"]).stem
    slug = re.sub(r"[^a-z0-9]+", "_", stem.lower()).strip("_")
    return f"{slug}_{row['tr_id'].lower()}"


def _summary_line(row: dict[str, Any]) -> str:
    params = row["params"]
    required = ", ".join(p["name"] for p in params if p["required"]) or "none"
    optional = ", ".join(p["name"] for p in params if not p["required"]) or "none"
    label_file = f"{row['domain']}_tr_labels.py"
    if row["method"] == "WS":
        fields = ", ".join(row["response"]["fields"]) or "none"
        return (
            f"WS tr_id={row['tr_id']}. Korean label: see generated/{label_file}. "
            f"Required parameters: {required}. Response fields: {fields}."
        )
    containers = ", ".join(row["response"]["containers"]) or "none"
    return (
        f"{row['method']} {row['path']} (tr_id={row['tr_id']}). "
        f"Korean label: see generated/{label_file}. "
        f"Required: {required}. Optional: {optional}. Response containers: {containers}."
    )


_DOC_WRAP_WIDTH = 88  # ruff E501(line-length=100)은 동아시아 폭 문자를 2로 센다 -- 들여쓰기
# 8칸을 빼고도 안전하도록 문자수가 아니라 표시폭(_display_width) 기준으로 감싼다.

# task-1990/ADR-2026-09-07-A 이후 재발 방지 가드(fail-closed). `_summary_line`이
# method/path/param 이름/containers/fields를 그대로 이어붙이므로, BR-11 기계 추출이
# 언젠가 이 필드 중 하나에 한글을 흘리면(예: 레이블 텍스트가 필드명으로 잘못 매핑)
# 조용히 `src/`에 한글 독스트링을 다시 찍어 code_language 래칫을 재발시킨다. 그
# 회귀는 별도 CI 단계(check_code_language.py)에서만 드러나 원인 추적이 늦어지므로,
# 생성 시점에 즉시 죽여 원인 행을 알려준다.
_HANGUL = re.compile(r"[가-힣]")


def _display_width(text: str) -> int:
    return sum(2 if unicodedata.east_asian_width(ch) in ("W", "F") else 1 for ch in text)


def _wrap_display(text: str, max_width: int) -> list[str]:
    """`textwrap.wrap`은 문자수만 세어 한글 등 폭 2 문자가 섞이면 실제 렌더 폭을
    과소평가한다 -- 표시폭 기준으로 직접 감싼다(순수 함수, 결정론)."""
    lines: list[str] = []
    current = ""
    current_width = 0
    for word in text.split(" "):
        word_width = _display_width(word)
        if word_width > max_width:
            if current:
                lines.append(current)
                current, current_width = "", 0
            chunk = ""
            chunk_width = 0
            for ch in word:
                ch_width = _display_width(ch)
                if chunk_width + ch_width > max_width and chunk:
                    lines.append(chunk)
                    chunk, chunk_width = "", 0
                chunk += ch
                chunk_width += ch_width
            current, current_width = chunk, chunk_width
            continue
        sep_width = 1 if current else 0
        if current and current_width + sep_width + word_width > max_width:
            lines.append(current)
            current, current_width = word, word_width
        else:
            current = f"{current} {word}" if current else word
            current_width += sep_width + word_width
    if current:
        lines.append(current)
    return lines or [text]


def _docstring_lines(row: dict[str, Any], indent: str) -> list[str]:
    summary = _summary_line(row).replace('"""', "'''")
    if _HANGUL.search(summary):
        raise KisGenerateError(
            f"{row['tr_id']}: docstring summary contains Hangul -- would regress the "
            "code_language ratchet (ADR-2026-09-07-A). Check upstream extraction for "
            "non-ASCII data in method/path/params/containers/fields."
        )
    wrapped = _wrap_display(summary, _DOC_WRAP_WIDTH)
    lines = [
        f'{indent}"""Auto-generated by BR-12 (ADR-2026-09-06-I D7).',
        f"{indent}Unverified: real-account round trip not confirmed.",
    ]
    lines.extend(f"{indent}{w}" for w in wrapped)
    lines.append(f'{indent}"""')
    return lines


def render_rest_method(row: dict[str, Any]) -> list[str]:
    if row["method"] not in ("GET", "POST"):
        raise KisGenerateError(f"{row['tr_id']}: 지원하지 않는 HTTP 메서드 {row['method']!r}")
    name = _method_name(row)
    arg_name = "params" if row["method"] == "GET" else "body"
    lines = [""]
    if is_order_method(row):
        lines.append("    @require_paper_sandbox")
    lines.extend(
        [
            f"    async def {name}(",
            "        self, params: dict[str, Any] | None = None",
            "    ) -> dict[str, Any]:",
        ]
    )
    lines.extend(_docstring_lines(row, "        "))
    lines.extend(
        [
            "        return await self._request(",
            f'            "{row["method"]}",',
            f'            "{row["path"]}",',
            f'            "{row["tr_id"]}",',
            f"            {arg_name}=params or {{}},",
            "        )",
        ]
    )
    return lines


def render_ws_method(row: dict[str, Any]) -> list[str]:
    if row["method"] != "WS":
        raise KisGenerateError(f"{row['tr_id']}: WS 렌더러에 비-WS 행 전달됨")
    name = _method_name(row)
    lines = [
        "",
        f"    async def {name}(",
        "        self,",
        "        tr_key: str,",
        "        callback: MessageHandler,",
        "        *,",
        "        on_reconnecting: ReconnectHook | None = None,",
        "        on_reconnected: ReconnectHook | None = None,",
        "        connect_fn: ConnectFn = _connect,",
        "    ) -> None:",
    ]
    lines.extend(_docstring_lines(row, "        "))
    lines.extend(
        [
            "        approval_key = await self.get_ws_approval_key()",
            "        url = WS_PAPER_URL if self._is_paper_trading else WS_REAL_URL",
            "        subscribe_msg = _build_subscribe_message(",
            f'            approval_key, "{row["tr_id"]}", tr_key',
            "        )",
            "",
            "        async def _on_frame(raw: str) -> None:",
            "            await callback(raw)",
            "",
            "        await _run_kis_ws_subscription(",
            "            url,",
            "            subscribe_msg,",
            "            _on_frame,",
            "            connect_fn=connect_fn,",
            "            on_reconnecting=on_reconnecting,",
            "            on_reconnected=on_reconnected,",
            "        )",
        ]
    )
    return lines


def is_order_method(row: dict[str, Any]) -> bool:
    """BR-12 리프(review:1971 REJECT 후속) -- 주문성 TR 판정.

    KIS TR 기준 목록 안 POST 메서드 48건은 예외 없이 매수/매도/정정/취소/예약주문
    (레이블에 "주문" 포함)이다. 이 저장소 안에서는 method == "POST"가 곧
    주문성이라는 뜻이라 이름 규칙에 기대지 않는다(fail-closed 원칙 -- 분류가
    모호하면 가드를 붙이는 쪽이 안전하다, decision 참조). GET/WS는 조회·구독뿐이라
    대상에서 뺀다."""
    return bool(row["method"] == "POST")


def render_method(row: dict[str, Any]) -> list[str]:
    return render_ws_method(row) if row["method"] == "WS" else render_rest_method(row)
