"""BR-12(ADR-2026-09-06-I D7) 청크 파일 조립 -- `kis_generate_adapters.py`에서
분할됨(CLAUDE.md 파일 정책, 500줄 경고선).

행 목록을 파일당 300줄 상한(BR-12 DoD)에 맞춰 청크로 나누고, 청크 하나를
mixin 파일 텍스트로, 그리고 청크 목록을 `__init__.py` 파사드로 조립한다.
메서드 한 개짜리 텍스트 렌더링은 `kis_rendering.py`가 맡는다.
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from types import ModuleType
from typing import Any


def _load_module(name: str, path: Path) -> ModuleType:
    """`sys.modules`에 이미 있으면 재사용한다(`kis_generate_adapters._load_module`과
    동일 이유 -- 클래스 정체성 분열 방지)."""
    existing = sys.modules.get(name)
    if existing is not None:
        return existing
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"모듈 로드 실패: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


_rendering = _load_module("kis_rendering", Path(__file__).resolve().parent / "kis_rendering.py")
KisGenerateError = _rendering.KisGenerateError
_pascal = _rendering._pascal
is_order_method = _rendering.is_order_method
render_method = _rendering.render_method

# 파일당 300줄 상한(BR-12 DoD) — 헤더(모듈 docstring+import)에 넉넉히 40줄을 남기고
# 본문(메서드 텍스트)은 260줄 예산으로 청크를 채운다.
_FILE_LINE_CAP = 300
_CHUNK_BODY_BUDGET = 260


def _chunk_rows(rows: list[dict[str, Any]]) -> list[list[dict[str, Any]]]:
    """tr_id 오름차순을 유지한 채 라인 예산으로 그리디 분할(결정론)."""
    chunks: list[list[dict[str, Any]]] = []
    current: list[dict[str, Any]] = []
    current_lines = 0
    for row in rows:
        rendered = render_method(row)
        if current and current_lines + len(rendered) > _CHUNK_BODY_BUDGET:
            chunks.append(current)
            current = []
            current_lines = 0
        current.append(row)
        current_lines += len(rendered)
    if current:
        chunks.append(current)
    return chunks


def render_chunk_file(
    domain: str, idx: int, rows: list[dict[str, Any]], *, file_line_cap: int = _FILE_LINE_CAP
) -> str:
    has_rest = any(r["method"] != "WS" for r in rows)
    has_ws = any(r["method"] == "WS" for r in rows)
    has_order = any(is_order_method(r) for r in rows)
    protocol_bases = sorted(
        name for name, flag in (("_KISRestHost", has_rest), ("_KISWsHost", has_ws)) if flag
    )
    class_name = f"KISGenerated{_pascal(domain)}{idx:02d}Mixin"

    lines: list[str] = [
        f'"""Auto-generated by BR-12 (ADR-2026-09-06-I D7) -- {domain} chunk {idx:02d}',
        "of TRs not yet implemented.",
        "",
        "`scripts/kis_generate_adapters.py` generated this from",
        "`docs/design/kis_tr_reference.json` (BR-11) -- do not hand-edit (a regeneration",
        "overwrites it). Only request assembly is done, using values extracted mechanically",
        "from the example scripts; responses are returned unparsed -- field-level type",
        "mapping is domain knowledge left to the verification leaves (BR-13~15) once a real",
        "account is available.",
        '"""',
        "from __future__ import annotations",
        "",
    ]
    if has_rest:
        lines += ["from typing import Any", ""]
    first_party: list[str] = []
    if has_order:
        first_party.append("from src.exchanges.common.live_guard import require_paper_sandbox")
    first_party.append(
        f"from src.exchanges.kis.generated._protocols import {', '.join(protocol_bases)}"
    )
    if has_ws:
        first_party.append(
            "from src.exchanges.kis.websocket_connection import (\n"
            "    ConnectFn,\n"
            "    MessageHandler,\n"
            "    ReconnectHook,\n"
            "    _connect,\n"
            "    _run_kis_ws_subscription,\n"
            ")"
        )
        first_party.append(
            "from src.exchanges.kis.websocket_mixin import (\n"
            "    WS_PAPER_URL,\n"
            "    WS_REAL_URL,\n"
            ")"
        )
        first_party.append(
            "from src.exchanges.kis.websocket_parsing import _build_subscribe_message"
        )
    lines += first_party
    lines += ["", "", f"class {class_name}({', '.join(protocol_bases)}):"]
    for row in rows:
        lines.extend(render_method(row))
    lines.append("")
    text = "\n".join(lines)
    if text.count("\n") + 1 > file_line_cap:
        raise KisGenerateError(
            f"{domain} 청크 {idx:02d}: {text.count(chr(10)) + 1}줄 > {file_line_cap}줄 상한"
        )
    return text


_PROTOCOLS_MODULE = '''"""Auto-generated by BR-12 (ADR-2026-09-06-I D7) -- adapter interfaces for
generated mixins.

`scripts/kis_generate_adapters.py` generates this -- do not hand-edit. Explicitly
inheriting from a Protocol base (structural typing) means cross-mixin access like
`self._request`/`self._is_paper_trading` doesn't need `# type: ignore[attr-defined]` --
the real implementation is filled in by `KISAdapter`'s other mixins
(`_KISHTTPClient`/`KISWebSocketMixin`), which come earlier in the MRO (a design choice
to avoid growing the PLT-40 type-ignore budget ratchet).
"""
from __future__ import annotations

from typing import Any, Protocol


class _KISRestHost(Protocol):
    async def _request(
        self,
        method: str,
        path: str,
        tr_id: str,
        *,
        params: dict[str, Any] | None = None,
        body: dict[str, Any] | None = None,
    ) -> dict[str, Any]: ...


class _KISWsHost(Protocol):
    _is_paper_trading: bool

    async def get_ws_approval_key(self) -> str: ...
'''


def render_init_module(chunk_names: list[tuple[str, str]]) -> str:
    """`chunk_names`: (module_stem, class_name) 목록(파일 생성 순서와 동일)."""
    import_lines = [
        f"from src.exchanges.kis.generated.{stem} import (\n    {cls},\n)"
        for stem, cls in chunk_names
    ]
    # 미착수 0건(모든 TR이 수기 구현됨)이면 청크가 없다 -- 그때도 유효한 클래스가
    # 나오도록 빈 베이스는 object 하나로 채운다(구문 오류 방지).
    bases = ",\n    ".join(cls for _, cls in chunk_names) or "object"
    return "\n".join(
        [
            '"""Auto-generated by BR-12 (ADR-2026-09-06-I D7) -- combines the per-domain',
            "generated mixins into one.",
            "",
            "`scripts/kis_generate_adapters.py` generates this -- do not hand-edit. adapter.py",
            "only needs to inherit `KISGeneratedMixin` (a new chunk only regenerates this",
            "file; adapter.py itself does not change).",
            '"""',
            "from __future__ import annotations",
            "",
            *import_lines,
            "",
            "",
            "class KISGeneratedMixin(",
            f"    {bases},",
            "):",
            '    """Facade combining all BR-12 generated mixins (per-domain chunks)."""',
            "",
        ]
    )
